name: Build supported Qt versions
on: [push, pull_request]

jobs:
  qt5:
    name: Qt 5
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Still compile Qt 5.15.2 because archive names have changed starting from Qt 5.15.3, due to Qt changing their license
        version: [5.12.12, 5.14.2, 5.15.2, 5.15.4]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Enable Ubuntu source repositories
        run: |
          sudo sed -e 's/#.*deb-src/deb-src/' -i /etc/apt/sources.list
      - name: Install build dependency packages
        run: |
          sudo apt update
          sudo apt build-dep qt5-default
          sudo apt install bison flex gperf libclang-dev libdbus-1-dev libnss3-dev libxcb-util-dev libxcb-xinerama0-dev libxcomposite-dev libxcursor-dev libxkbcommon-dev libxtst-dev patchelf
      - name: Build Qt ${{ matrix.version }}
        run: ./Qt_Builder.sh ${{ matrix.version }}

  qt6:
    name: Qt 6
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [6.0.4, 6.1.3, 6.2.4, 6.3.1]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Enable Ubuntu source repositories
        run: |
          sudo sed -e 's/#.*deb-src/deb-src/' -i /etc/apt/sources.list
      - name: Install build dependency packages
        run: |
          sudo apt update
          sudo apt build-dep qtbase5-dev
          sudo apt install bison cmake flex gperf libb2-dev libclang-dev libclang-11-dev libclang-12-dev libdbus-1-dev libdirectfb-dev libgstreamer1.0-dev libnss3-dev libsystemd-dev libts-dev libxcb-util-dev libxcb-xinerama0-dev libxcomposite-dev libxcursor-dev libxkbcommon-dev libxcb-composite0-dev libxcb-cursor-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-ewmh-dev libxcb-present-dev libxcb-record0-dev libxcb-res0-dev libxcb-screensaver0-dev libxcb-xf86dri0-dev libxcb-xtest0-dev libxcb-xv0-dev libxcb-xvmc0-dev libxtst-dev ninja-build patchelf xcb
      - name: Build Qt ${{ matrix.version }}
        run: ./Qt_Builder.sh ${{ matrix.version }}
